services:
  - type: web
    name: yukki-music-bot
    env: python
    plan: free

    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: python -m YukkiMusic

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"

      - key: PYTHONUNBUFFERED
        value: "1"

      # ==== Telegram Config ====
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SESSION_NAME
        value: yukki
